export const FOLLOWUP_FIELDS = [
  {key:"visit_date", label:"Muayene tarihi", type:"date", required:true},
  {key:"semptom_devam", label:"Semptom devam", type:"bool"},
  {key:"egzersiz_kisitliligi", label:"Egzersiz kısıtlılığı", type:"bool"},
  {key:"atak_sayisi", label:"Son kontrolden beri atak", type:"num"},
  {key:"pnomoni_sayisi", label:"Son kontrolden beri pnömoni", type:"num"},
  {key:"o2", label:"O2 ihtiyacı", type:"bool"},
  {key:"bipap", label:"BiPAP/NIV", type:"bool"},
  {key:"imv", label:"İnvaziv MV", type:"bool"},
  {key:"ecmo", label:"ECMO", type:"bool"},
  {key:"yeni_oksijen_ihtiyaci", label:"Yeni oksijen ihtiyacı", type:"bool"},
  {key:"sistemik_steroid_mgkg_gun", label:"Steroid dozu (mg/kg/gün)", type:"num"},
  {key:"sistemik_steroid_gun", label:"Steroid günü", type:"num"},
  {key:"sistemik_steroid_plan_gun", label:"Planlanan steroid günü", type:"num"},
  {key:"va", label:"Ağırlık (kg)", type:"num"},
  {key:"boy", label:"Boy (cm)", type:"num"},
  {key:"spo2", label:"SpO2 (%)", type:"num"},
  {key:"fev1", label:"FEV1 (%)", type:"num"},
  {key:"fvc", label:"FVC (%)", type:"num"},
  {key:"mef2575", label:"MEF25-75 (%)", type:"num"},
  {key:"klinik_gidis", label:"Klinik gidiş", type:"select", options:[
    {v:"", l:"Otomatik/boş"},
    {v:"iyi_stabil", l:"İyi/stabil"},
    {v:"persistan_semptom", l:"Persistan semptomlu"},
    {v:"alevlenmeli", l:"Alevlenmeli"},
    {v:"kotu_progresif", l:"Kötü/progresif"},
    {v:"exitus", l:"Exitus"},
  ]},
  {key:"notlar", label:"Not", type:"text"},
]

export const PFT_FIELDS = [
  {key:"test_date", label:"Tetkik tarihi", type:"date", required:true},
  {key:"test_type", label:"Tetkik tipi", type:"select", options:[
    {v:"", l:"—"},
    {v:"bazal", l:"Bazal"},
    {v:"izlem", l:"İzlem"},
    {v:"bronkodilatator", l:"BD sonrası"},
  ]},
  {key:"fev1", label:"FEV1 (%)", type:"num"},
  {key:"fev1_z", label:"FEV1 z-skor", type:"num"},
  {key:"fvc", label:"FVC (%)", type:"num"},
  {key:"fvc_z", label:"FVC z-skor", type:"num"},
  {key:"fev1_fvc", label:"FEV1/FVC", type:"num"},
  {key:"fev1_fvc_z", label:"FEV1/FVC z-skor", type:"num"},
  {key:"mef2575", label:"MEF25-75 (%)", type:"num"},
  {key:"mef2575_z", label:"MEF25-75 z-skor", type:"num"},
  {key:"bd_fev1", label:"BD FEV1 değişim (%)", type:"num"},
  {key:"bd_mef2575", label:"BD MEF25-75 değişim (%)", type:"num"},
  {key:"dlco", label:"DLCO (%)", type:"num"},
  {key:"dlco_z", label:"DLCO z-skor", type:"num"},
  {key:"rv", label:"RV (%)", type:"num"},
  {key:"tlc", label:"TLC (%)", type:"num"},
  {key:"rv_tlc", label:"RV/TLC (%)", type:"num"},
  {key:"notlar", label:"Not", type:"text"},
]

export const DOSING_FREQUENCY_OPTIONS = [
  {v:"1", l:"1x"},
  {v:"2", l:"2x"},
  {v:"3", l:"3x"},
  {v:"4", l:"4x"},
]

export const FIELD_GROUPS = {
  genel: {
    label: "Genel", fields: [
      {key:"hasta_id", label:"Hasta ID", type:"text", required:true},
      {key:"registry_type", label:"Registry kolu", type:"select", required:true, options:[{v:"PIBO",l:"PIBO Registry"},{v:"PTBO",l:"HSCT / PTBO-BOS Registry"}]},
      {key:"pibo", label:"PIBO", type:"bool", required:true, readonly:true},
      {key:"ptbo", label:"HSCT kohortu", type:"bool", required:true, readonly:true},
      {key:"aydinlatilmis_onam_alindi", label:"Aydınlatılmış onam alındı", type:"bool", required:true},
      {key:"cinsiyet", label:"Cinsiyet", type:"select", options:[{v:"e",l:"Erkek"},{v:"k",l:"Kız"}]},
      {key:"yabanci", label:"Yabancı uyruklu", type:"bool"},
      {key:"dogum_tarihi", label:"Doğum tarihi", type:"date", required:true},
      {key:"semptom_baslangic_tarihi", label:"Yakınmaların başladığı tarih", type:"date"},
      {key:"ilk_muayene_tarihi", label:"İlk çocuk göğüs muayene tarihi", type:"date"},
      {key:"tani_tarihi", label:"PIBO veya BOS/PTBO tanı tarihi", type:"date"},
      {key:"bt_tarihi", label:"BT inceleme tarihi", type:"date"},
      {key:"bronkoskopi_tarihi", label:"Bronkoskopi tarihi", type:"date"},
      {key:"yas_ay", label:"Tanı yaşı (ay)", type:"num", readonly:true},
      {key:"tani_yas_gun", label:"Tanı anındaki yaş (gün)", type:"num", readonly:true},
      {key:"semptom_tani_gun", label:"Semptom → tanı (gün)", type:"num", readonly:true},
      {key:"muayene_tani_gun", label:"İlk muayene → tanı (gün)", type:"num", readonly:true},
      {key:"muayene_bronkoskopi_gun", label:"İlk muayene → bronkoskopi (gün)", type:"num", readonly:true},
      {key:"semptom_bronkoskopi_gun", label:"Semptom → bronkoskopi (gün)", type:"num", readonly:true},
    ]
  },
  vitaller: {
    label: "Vitaller & Antropometri", fields: [
      {key:"spo2_bas", label:"SpO2 (%)", type:"num"},
      {key:"ates_bas", label:"Ateş (°C)", type:"num"},
      {key:"solunum_sayisi_bas", label:"Solunum sayısı (/dk)", type:"num"},
      {key:"kalp_tepe_atimi_bas", label:"Kalp tepe atımı (/dk)", type:"num"},
      {key:"va_bas", label:"Ağırlık başlangıç (kg)", type:"num"},
      {key:"va_z_bas", label:"Ağırlık z-skor başlangıç", type:"num", readonly:true},
      {key:"va_bit", label:"Ağırlık bitiş (kg)", type:"num"},
      {key:"va_z_bit", label:"Ağırlık z-skor bitiş", type:"num", readonly:true},
      {key:"boy_bas", label:"Boy başlangıç (cm)", type:"num"},
      {key:"boy_z_bas", label:"Boy z-skor başlangıç", type:"num", readonly:true},
      {key:"boy_bit", label:"Boy bitiş (cm)", type:"num"},
      {key:"boy_z_bit", label:"Boy z-skor bitiş", type:"num", readonly:true},
      {key:"vki_bas", label:"VKI başlangıç", type:"num", readonly:true},
      {key:"vki_z_bas", label:"VKI z-skor başlangıç", type:"num", readonly:true},
      {key:"vki_bit", label:"VKI bitiş", type:"num", readonly:true},
      {key:"vki_z_bit", label:"VKI z-skor bitiş", type:"num", readonly:true},
      {key:"vki_fark", label:"VKI z-skor fark", type:"num", readonly:true},
      {key:"premature", label:"Prematüre doğum", type:"bool"},
      {key:"gestasyon_haftasi", label:"Gestasyon haftası", type:"num"},
      {key:"dogum_agirligi_g", label:"Doğum ağırlığı (g)", type:"num"},
      {key:"yenidogan_yogun_bakim", label:"Yenidoğan yoğun bakım", type:"bool"},
      {key:"neonatal_oksijen", label:"Neonatal oksijen", type:"bool"},
      {key:"bpd_oykusu", label:"BPD öyküsü", type:"bool"},
    ]
  },
  akut: {
    label: "Akut Dönem", registry:"PIBO", fields: [
      {key:"akut_asye_tarihi", label:"İlk akut ASYE tarihi", type:"date"},
      {key:"ates_suresi_gun", label:"Ateş süresi (gün)", type:"num"},
      {key:"agir_pnomoni", label:"Ağır pnömoni", type:"bool"},
      {key:"ilk_akut_asye_yatis_gun", label:"İlk akut ASYE yatış süresi (gün)", type:"num"},
      {key:"tekrarlayan_pnomoni", label:"Tekrarlayan pnömoni öyküsü", type:"bool"},
      {key:"pnomoni_atak_sayisi", label:"Toplam pnömoni atağı", type:"num"},
      {key:"toplam_pnomoni_yatis_gun", label:"Toplam pnömoni yatış süresi (gün)", type:"num"},
      {key:"akut_hipoksemi", label:"Akut hipoksemi", type:"bool"},
      {key:"akut_yatis", label:"Akut hastane yatışı", type:"bool"},
      {key:"cocuk_yogun_bakim", label:"Çocuk yoğun bakım", type:"bool"},
      {key:"akut_oksijen", label:"Akut oksijen", type:"bool"},
      {key:"akut_hfnc", label:"Akut HFNC", type:"bool"},
      {key:"akut_niv", label:"Akut NIV/BiPAP", type:"bool"},
      {key:"akut_imv", label:"Akut invaziv MV", type:"bool"},
      {key:"akut_ivig", label:"Akut IVIG", type:"bool"},
      {key:"akut_glukokortikoid", label:"Akut glukokortikoid", type:"bool"},
      {key:"yatis", label:"Toplam hastane yatışı", type:"bool"},
      {key:"o2", label:"O2 desteği", type:"bool"},
      {key:"bipap", label:"BiPAP", type:"bool"},
      {key:"imv", label:"İnvaziv MV", type:"bool"},
      {key:"ecmo", label:"ECMO", type:"bool"},
    ]
  },
  etiyoloji: {
    label: "Etiyoloji", registry:"PIBO", fields: [
      {key:"etken_adenovirus", label:"Adenovirüs", type:"bool"},
      {key:"etken_mycoplasma", label:"Mycoplasma pneumoniae", type:"bool"},
      {key:"etken_rsv", label:"RSV", type:"bool"},
      {key:"etken_rinovirus", label:"Rinovirus", type:"bool"},
      {key:"etken_pnomokok", label:"Pnömokok", type:"bool"},
      {key:"etken_cmv", label:"CMV", type:"bool"},
      {key:"etken_influenza", label:"İnfluenza", type:"bool"},
      {key:"etken_parainfluenza", label:"Parainfluenza", type:"bool"},
      {key:"etken_kizamik", label:"Kızamık", type:"bool"},
      {key:"etken_metapneumovirus", label:"Metapneumovirus", type:"bool"},
      {key:"etken_covid", label:"COVID-19", type:"bool"},
      {key:"etken_varicella", label:"Varicella", type:"bool"},
      {key:"etken_ebv", label:"EBV", type:"bool"},
      {key:"etken_bakteri", label:"Bakteriyel etken", type:"bool"},
      {key:"koenfeksiyon", label:"Ko-enfeksiyon", type:"bool"},
      {key:"etken_diger", label:"Diğer etken", type:"text"},
      {key:"hsct", label:"HSCT", type:"bool"},
      {key:"solid_tx", label:"Solid Tx", type:"bool"},
      {key:"gvhd", label:"GVHD", type:"bool"},
      {key:"gvhd_yeri", label:"GVHD yeri", type:"text"},
      {key:"tx1_tani_gun", label:"1.Tx → tanı (gün, negatif=önce)", type:"num"},
      {key:"gvhd_tani_gun", label:"GVHD → tanı (gün, negatif=önce)", type:"num"},
    ]
  },
  radyoloji: {
    label: "Radyoloji (BT)", registry:"PIBO", fields: [
      {key:"bt_infiltrasyon", label:"İnfiltrasyon", type:"bool"},
      {key:"bt_mozaik", label:"Mozaik perfüzyon/attenüasyon", type:"bool"},
      {key:"bt_air_trapping", label:"Air trapping", type:"bool"},
      {key:"bt_bronduvar_kalinlasma", label:"Bronş duvar kalınlaşması", type:"bool"},
      {key:"bt_atelektazi", label:"Atelektazi", type:"bool"},
      {key:"bt_sag_orta_atelektazi", label:"Sağ orta lob atelektazi", type:"bool"},
      {key:"bt_lingula_atelektazi", label:"Lingula atelektazi", type:"bool"},
      {key:"bt_diger_atelektazi", label:"Diğer atelektazi", type:"bool"},
      {key:"bt_bronsektazi", label:"Bronşektazi", type:"bool"},
      {key:"bt_sag_orta_bronsektazi", label:"Sağ orta lob bronşektazi", type:"bool"},
      {key:"bt_lingula_bronsektazi", label:"Lingula bronşektazi", type:"bool"},
      {key:"bt_diger_bronsektazi", label:"Diğer bronşektazi", type:"bool"},
      {key:"bt_buyuk_lobar_konsolidasyon", label:"Büyük lobar konsolidasyon", type:"bool"},
      {key:"bt_diffuz_bronsiolit", label:"Diffüz bronşiolit", type:"bool"},
      {key:"bhalla_skoru", label:"Bhalla skoru", type:"num", note:"rad"},
      {key:"teper_skoru", label:"Teper skoru", type:"num", note:"rad"},
      {key:"webb_skoru", label:"WEBB skoru", type:"num", note:"rad"},
    ]
  },
  tedavi: {
    label: "Tedavi", registry:"PIBO", fields: [
      {key:"sistemik_steroid", label:"Sistemik steroid aldı", type:"bool", readonly:true},
      {key:"sistemik_steroid_mgkg_gun", label:"Sistemik steroid dozu (mg/kg/gün)", type:"num"},
      {key:"sistemik_steroid_gun", label:"Sistemik steroid aldığı gün", type:"num"},
      {key:"sistemik_steroid_plan_gun", label:"Planlanan sistemik steroid günü", type:"num"},
      {key:"kumulatif_sistemik_steroid_mgkg", label:"Kümülatif sistemik steroid (mg/kg)", type:"num", readonly:true},
      {key:"pulse_steroid", label:"Pulse steroid aldı", type:"bool", readonly:true},
      {key:"pulse_steroid_mgkg", label:"Pulse steroid dozu (mg/kg)", type:"select", options:[
        {v:"10", l:"10 mg/kg"},
        {v:"20", l:"20 mg/kg"},
        {v:"30", l:"30 mg/kg"},
      ]},
      {key:"tanidan_once_antibiyotik", label:"Tanı öncesi antibiyotik", type:"bool"},
      {key:"inhale_steroid_aldi", label:"İnhale steroid aldı", type:"bool", readonly:true},
      {key:"flutikazon_neb_2mg_adet_gun", label:"Flutikazon neb 2 mg sıklık", type:"select", options:DOSING_FREQUENCY_OPTIONS},
      {key:"flutikazon_neb_2mg_gun", label:"Flutikazon neb 2 mg gün", type:"num"},
      {key:"flutikazon_neb_05mg_adet_gun", label:"Flutikazon neb 0.5 mg sıklık", type:"select", options:DOSING_FREQUENCY_OPTIONS},
      {key:"flutikazon_neb_05mg_gun", label:"Flutikazon neb 0.5 mg gün", type:"num"},
      {key:"flutikazon_neb_toplam_mcg", label:"Neb flutikazon toplam (mcg)", type:"num", readonly:true},
      {key:"flutikazon_inhaler_125_puff_gun", label:"Flutikazon 125 mcg sıklık", type:"select", options:DOSING_FREQUENCY_OPTIONS},
      {key:"flutikazon_inhaler_125_gun", label:"Flutikazon 125 mcg gün", type:"num"},
      {key:"flutikazon_inhaler_50_puff_gun", label:"Flutikazon 50 mcg sıklık", type:"select", options:DOSING_FREQUENCY_OPTIONS},
      {key:"flutikazon_inhaler_50_gun", label:"Flutikazon 50 mcg gün", type:"num"},
      {key:"flutikazon_inhaler_toplam_mcg", label:"İnhaler flutikazon toplam (mcg)", type:"num", readonly:true},
      {key:"seretide_125_puff_gun", label:"Seretide 125 sıklık", type:"select", options:DOSING_FREQUENCY_OPTIONS},
      {key:"seretide_125_gun", label:"Seretide 125 gün", type:"num"},
      {key:"seretide_250_puff_gun", label:"Seretide 250 sıklık", type:"select", options:DOSING_FREQUENCY_OPTIONS},
      {key:"seretide_250_gun", label:"Seretide 250 gün", type:"num"},
      {key:"seretide_aldi", label:"Seretide aldı", type:"bool", readonly:true},
      {key:"seretide_toplam_flutikazon_mcg", label:"Seretide flutikazon toplam (mcg)", type:"num", readonly:true},
      {key:"toplam_inhale_steroid_mcg", label:"Toplam inhale steroid (mcg)", type:"num", readonly:true},
      {key:"azitromisin_aldi", label:"Azitromisin", type:"bool"},
      {key:"azitro_bitis_tarihi", label:"Azitromisin bitiş tarihi", type:"date"},
      {key:"azitro_bitis_tani_gun", label:"Tanı -> azitromisin bitişi (gün)", type:"num", readonly:true},
      {key:"montelukast_aldi", label:"Montelukast", type:"bool"},
      {key:"fam_aldi", label:"FAM aldı", type:"bool", readonly:true},
      {key:"bronchomunal", label:"Bronchomunal", type:"bool"},
      {key:"ivig_aldi", label:"IVIG verildi", type:"bool"},
      {key:"ivig_aliyor", label:"IVIG halen alıyor", type:"bool"},
      {key:"ventolin_aldi", label:"Ventolin", type:"bool"},
      {key:"tedavi_suresi_gun", label:"Tedavi süresi (gün)", type:"num"},
    ]
  },
  bal: {
    label: "BAL", registry:"PIBO", fields: [
      {key:"bal_ureme", label:"BAL üreme", type:"bool"},
      {key:"bal_coklu_ureme", label:"BAL çoklu üreme", type:"bool"},
      {key:"bal_kultur1", label:"BAL kültür 1", type:"text"},
      {key:"bal_kultur2", label:"BAL kültür 2", type:"text"},
      {key:"bal_kultur3", label:"BAL kültür 3", type:"text"},
      {key:"bal_h_influenza", label:"H. influenzae üremesi", type:"bool"},
      {key:"bal_m_catarrhalis", label:"M. catarrhalis üremesi", type:"bool"},
      {key:"rpcr", label:"Respiratuvar PCR", type:"bool"},
      {key:"bal_solunum_pcr", label:"BAL solunum PCR sonucu", type:"text"},
      {key:"bal_cmv_pcr", label:"BAL CMV PCR", type:"bool"},
      {key:"bal_pjir", label:"BAL PJİR", type:"bool"},
      {key:"bal_lipid_ym", label:"BAL lipid yüklü makrofaj", type:"bool"},
      {key:"bal_hemosiderin_ym", label:"BAL hemosiderin yüklü makrofaj", type:"bool"},
      {key:"bal_lenfosit_subset", label:"BAL lenfosit subset yapıldı", type:"bool"},
      {key:"bal_lenfopeni", label:"BAL lenfopeni", type:"bool"},
      {key:"lokosit", label:"BAL lökosit sayısı", type:"num"},
      {key:"lenfosit_oran", label:"BAL lenfosit oranı (%)", type:"num"},
      {key:"notrofil_oran", label:"BAL nötrofil oranı (%)", type:"num"},
      {key:"eozinofil_oran", label:"BAL eozinofil oranı (%)", type:"num"},
      {key:"bal_cd3", label:"BAL CD3", type:"num"},
      {key:"bal_cd4", label:"BAL CD4", type:"num"},
      {key:"bal_cd8", label:"BAL CD8", type:"num"},
      {key:"bal_cd4_cd8", label:"BAL CD4/CD8", type:"num"},
      {key:"bal_cd19", label:"BAL CD19", type:"num"},
      {key:"bal_cd16_cd56", label:"BAL CD16/CD56", type:"num"},
      {key:"bal_cd45", label:"BAL CD45", type:"num"},
      {key:"bal_cd56", label:"BAL CD56", type:"num"},
      {key:"bal_cd22", label:"BAL CD22", type:"num"},
      {key:"bal_cd20", label:"BAL CD20", type:"num"},
      {key:"bal_cd16", label:"BAL CD16", type:"num"},
      {key:"bal_cd3_hladr", label:"BAL CD3+HLA-DR+", type:"num"},
    ]
  },
  immunoloji: {
    label: "İmmünoloji & Lab", registry:"PIBO", fields: [
      {key:"imun_yetmezlik", label:"İmmün yetmezlik", type:"bool"},
      {key:"imdef", label:"İmmün yetmezlik açıklaması", type:"text"},
      {key:"tani_surecinde_imyetm", label:"Tanı sürecinde immün yetmezlik", type:"bool"},
      {key:"imdefdr", label:"İmmün yetmezlik tedavisi/notu", type:"text"},
      {key:"astim", label:"Astım", type:"bool"},
      {key:"alerjik_rinit", label:"Alerjik rinit", type:"bool"},
      {key:"atopik_dermatit", label:"Atopik dermatit", type:"bool"},
      {key:"kisisel_atopi", label:"Kişisel atopi", type:"bool"},
      {key:"aile_atopi", label:"Aile atopi", type:"bool"},
      {key:"spesifik_ige_pozitif", label:"Spesifik IgE pozitif", type:"bool"},
      {key:"iga", label:"IgA (g/L)", type:"num", hint:"g/L olarak girin; örn 0.48. Ondalık için nokta kullanın."},
      {key:"iga_dusuk", label:"IgA düşük", type:"bool", readonly:true},
      {key:"igm", label:"IgM (g/L)", type:"num", hint:"g/L olarak girin; örn 1.49. Ondalık için nokta kullanın."},
      {key:"igm_dusuk", label:"IgM düşük", type:"bool", readonly:true},
      {key:"igg", label:"IgG (g/L)", type:"num", hint:"g/L olarak girin; örn 7.91. Yaşa göre düşük hesabı otomatik yapılır."},
      {key:"igg_dusuk", label:"IgG düşük", type:"bool", readonly:true},
      {key:"ige", label:"IgE (IU/mL)", type:"num", hint:"IU/mL olarak girin; örn 55.4."},
      {key:"igg1", label:"IgG1 (g/L)", type:"num", hint:"g/L olarak girin; örn 9.89. Sistem mg/dL referansa çevirir."},
      {key:"igg1_dusuk", label:"IgG1 düşük", type:"bool", readonly:true},
      {key:"igg2", label:"IgG2 (g/L)", type:"num", hint:"g/L olarak girin; örn 0.95. Ondalık için nokta kullanın."},
      {key:"igg2_dusuk", label:"IgG2 düşük", type:"bool", readonly:true},
      {key:"igg3", label:"IgG3 (g/L)", type:"num", hint:"g/L olarak girin; örn 0.77. Ondalık için nokta kullanın."},
      {key:"igg3_dusuk", label:"IgG3 düşük", type:"bool", readonly:true},
      {key:"igg4", label:"IgG4 (g/L)", type:"num", hint:"g/L olarak girin; örn 0.57. Ondalık için nokta kullanın."},
      {key:"igg4_dusuk", label:"IgG4 düşük", type:"bool", readonly:true},
      {key:"cbc_bk", label:"Lökosit (/mm³)", type:"num"},
      {key:"cbc_neu", label:"Nötrofil (/mm³)", type:"num"},
      {key:"cbc_lym", label:"Lenfosit (/mm³)", type:"num"},
      {key:"lym_abs_dusuk", label:"Lenfosit düşük", type:"bool", readonly:true},
      {key:"cbc_eos", label:"Eozinofil (/mm³)", type:"num"},
      {key:"cbc_nlr", label:"NLR", type:"num", readonly:true},
      {key:"cd3", label:"Kan CD3 (%)", type:"num"},
      {key:"cd3_pct_dusuk", label:"CD3 % düşük", type:"bool", readonly:true},
      {key:"cd4", label:"Kan CD4 (%)", type:"num"},
      {key:"cd4_pct_dusuk", label:"CD4 % düşük", type:"bool", readonly:true},
      {key:"cd8", label:"Kan CD8 (%)", type:"num"},
      {key:"cd8_pct_dusuk", label:"CD8 % düşük", type:"bool", readonly:true},
      {key:"cd4_cd8", label:"Kan CD4/CD8", type:"num"},
      {key:"cd19", label:"Kan CD19", type:"num"},
      {key:"cd19_pct_dusuk", label:"CD19 % düşük", type:"bool", readonly:true},
      {key:"cd16_cd56", label:"Kan CD16/CD56", type:"num"},
      {key:"cd16_cd56_pct_dusuk", label:"CD16/56 % düşük", type:"bool", readonly:true},
      {key:"lswbc", label:"Lenfosit subset WBC", type:"num"},
      {key:"lslym_pct", label:"LS lenfosit %", type:"num"},
      {key:"lscd3_pct", label:"LS CD3 %", type:"num"},
      {key:"lscd3_abs", label:"LS CD3 abs", type:"num"},
      {key:"cd3_abs_dusuk", label:"CD3 abs düşük", type:"bool", readonly:true},
      {key:"lscd4_pct", label:"LS CD4 %", type:"num"},
      {key:"lscd4_abs", label:"LS CD4 abs", type:"num"},
      {key:"cd4_abs_dusuk", label:"CD4 abs düşük", type:"bool", readonly:true},
      {key:"lscd8_pct", label:"LS CD8 %", type:"num"},
      {key:"lscd8_abs", label:"LS CD8 abs", type:"num"},
      {key:"cd8_abs_dusuk", label:"CD8 abs düşük", type:"bool", readonly:true},
      {key:"lscd4_cd8", label:"LS CD4/CD8", type:"num"},
      {key:"lscd19", label:"LS CD19", type:"num"},
      {key:"cd19_abs_dusuk", label:"CD19 abs düşük", type:"bool", readonly:true},
      {key:"lscd56", label:"LS CD56", type:"num"},
      {key:"cd16_cd56_abs_dusuk", label:"CD16/56 abs düşük", type:"bool", readonly:true},
      {key:"lenfosit_subset_dusuk", label:"Lenfosit subset düşük var", type:"bool", readonly:true},
    ]
  },
  sft: {
    label: "SFT", fields: [
      {key:"sft_bas_tarihi", label:"Bazal SFT tarihi", type:"date"},
      {key:"fev1_bas", label:"FEV1 başlangıç (%)", type:"num"},
      {key:"fvc_bas", label:"FVC başlangıç (%)", type:"num"},
      {key:"mef2575_bas", label:"MEF25-75 başlangıç (%)", type:"num"},
      {key:"fev1_bd_bas", label:"Bazal BD FEV1 değişim (%)", type:"num"},
      {key:"mef2575_bd_bas", label:"Bazal BD MEF25-75 değişim (%)", type:"num"},
      {key:"dlco_bas", label:"DLCO başlangıç (%)", type:"num"},
      {key:"rv_bas", label:"RV başlangıç (%)", type:"num"},
      {key:"tlc_bas", label:"TLC başlangıç (%)", type:"num"},
      {key:"rv_tlc_bas", label:"RV/TLC başlangıç (%)", type:"num"},
      {key:"x5_bas", label:"X5 başlangıç", type:"num"},
      {key:"r5_bas", label:"R5 başlangıç", type:"num"},
      {key:"ax_bas", label:"AX başlangıç", type:"num"},
      {key:"sft_bit_tarihi", label:"Son SFT tarihi", type:"date"},
      {key:"fev1_bit", label:"FEV1 bitiş (%)", type:"num"},
      {key:"fvc_bit", label:"FVC bitiş (%)", type:"num"},
      {key:"mef2575_bit", label:"MEF25-75 bitiş (%)", type:"num"},
      {key:"bd_fev1", label:"BD FEV1 değişim bitiş (%)", type:"num"},
      {key:"bd_mef2575", label:"BD MEF25-75 değişim bitiş (%)", type:"num"},
      {key:"dlco_bit", label:"DLCO bitiş (%)", type:"num"},
      {key:"rv_bit", label:"RV bitiş (%)", type:"num"},
      {key:"tlc_bit", label:"TLC bitiş (%)", type:"num"},
      {key:"rv_tlc_bit", label:"RV/TLC bitiş (%)", type:"num"},
      {key:"x5_bit", label:"X5 bitiş", type:"num"},
      {key:"r5_bit", label:"R5 bitiş", type:"num"},
      {key:"ax_bit", label:"AX bitiş", type:"num"},
      {key:"xu_siddet", label:"Xu klinik şiddet (1-5)", type:"num", note:"kln"},
    ]
  },
  kardiyak_sonuc: {
    label: "Kardiyak & Sonuç", fields: [
      {key:"eko", label:"EKO yapıldı", type:"bool"},
      {key:"pht", label:"Pulmoner HT", type:"bool"},
      {key:"pap", label:"PAP (mmHg)", type:"num"},
      {key:"tedi_sonrasi_atak", label:"Tedavi sonrası atak sayısı", type:"num"},
      {key:"tedi_sonrasi_pnomoni", label:"Tedavi sonrası pnömoni sayısı", type:"num"},
      {key:"tedavi_sonucu", label:"Tedavi sonucu (1=iyi, 2=orta, 3=kötü)", type:"num"},
      {key:"semptom_devam", label:"Semptom devam ediyor", type:"bool"},
      {key:"ex", label:"Exitus", type:"bool"},
    ]
  },
  ptbo_tb: {
    label: "HSCT kohortu - TB", registry:"PTBO", fields: [
      {key:"akciger_goruntuleme_yapildi", label:"Akciğer görüntüleme yapıldı", type:"bool"},
      {key:"akciger_goruntuleme_tarihi", label:"Akciğer görüntüleme tarihi", type:"date"},
      {key:"akciger_goruntuleme_yontemi", label:"Görüntüleme yöntemi", type:"select", options:[
        {v:"akciger_grafisi", l:"Akciğer grafisi"},
        {v:"toraks_bt", l:"Toraks BT"},
        {v:"hrct", l:"HRCT"},
        {v:"diger", l:"Diğer"},
      ]},
      {key:"akciger_goruntuleme_bulgu", label:"Görüntüleme bulgusu", type:"text"},
      {key:"ppd_mm", label:"PPD endürasyon (mm)", type:"num"},
      {key:"ppd_sonuc", label:"PPD sonucu", type:"select", options:[
        {v:"negatif", l:"Negatif"},
        {v:"pozitif", l:"Pozitif"},
        {v:"supheli", l:"Şüpheli"},
        {v:"yapilmadi", l:"Yapılmadı"},
      ]},
      {key:"tb_igra_sonuc", label:"TB IGRA sonucu", type:"select", options:[
        {v:"negatif", l:"Negatif"},
        {v:"pozitif", l:"Pozitif"},
        {v:"indeterminate", l:"Belirsiz"},
        {v:"yapilmadi", l:"Yapılmadı"},
      ]},
      {key:"tb_igra_tarihi", label:"TB IGRA tarihi", type:"date"},
      {key:"tb_mikrobiyoloji_pozitif", label:"TB mikrobiyoloji pozitif", type:"bool"},
      {key:"tb_tedavi_baslangic_tarihi", label:"TB tedavi başlangıç tarihi", type:"date"},
      {key:"tb_tedavi_suresi_ay", label:"TB tedavi süresi (ay)", type:"num"},
    ]
  },
  ptbo_hsct: {
    label: "HSCT kohortu - Temel", registry:"PTBO", fields: [
      {key:"ptbo_altta_yatan_hastalik", label:"Altta yatan hastalık", type:"text"},
      {key:"ptbo_malignite_endikasyonu", label:"Malign endikasyon", type:"bool"},
      {key:"ptbo_hsct_tarihi", label:"Allojenik HSCT tarihi", type:"date", required:true},
      {key:"ptbo_donor_tipi", label:"Donör tipi", type:"select", options:[{v:"akraba",l:"Akraba"},{v:"akraba_disi",l:"Akraba dışı"},{v:"haplo",l:"Haploidentik"},{v:"kordon",l:"Kordon kanı"},{v:"diger",l:"Diğer"}]},
      {key:"ptbo_kok_hucre_kaynagi", label:"Kök hücre kaynağı", type:"select", options:[{v:"kemik_iligi",l:"Kemik iliği"},{v:"periferik_kan",l:"Periferik kan"},{v:"kordon",l:"Kordon kanı"},{v:"diger",l:"Diğer"}]},
      {key:"ptbo_kosullandirma_yogunlugu", label:"Koşullandırma yoğunluğu", type:"select", options:[{v:"myeloablatif",l:"Myeloablatif"},{v:"azaltilmis",l:"Azaltılmış yoğunluk"},{v:"bilinmiyor",l:"Bilinmiyor"}]},
      {key:"ptbo_onceki_akciger_hastaligi", label:"Önceden akciğer hastalığı", type:"bool"},
      {key:"ptbo_torasik_radyoterapi", label:"Torasik radyoterapi", type:"bool"},
      {key:"ptbo_kemo_akciger_toksisite", label:"Kemoterapi akciğer toksisitesi", type:"bool"},
      {key:"ptbo_akut_gvhd", label:"Akut GVHD", type:"bool"},
      {key:"ptbo_cgvhd", label:"Kronik GVHD", type:"bool"},
      {key:"ptbo_extrapulmoner_cgvhd", label:"Ekstrapulmoner cGVHD", type:"bool"},
      {key:"ptbo_cgvhd_organlari", label:"cGVHD organları", type:"text"},
      {key:"ptbo_sistemik_immunsupresyon", label:"Sistemik immünsüpresyon", type:"bool"},
      {key:"ptbo_immunsupresyon_ajanlari", label:"İmmünsüpresyon ajanları", type:"text"},
    ]
  },
  ptbo_pre_hsct: {
    label: "HSCT kohortu - Pre-HSCT akciğer", registry:"PTBO", fields: [
      {key:"ptbo_pre_hsct_sft_var", label:"Pre-HSCT spirometri var", type:"bool"},
      {key:"ptbo_pre_hsct_fev1_pct", label:"Pre-HSCT FEV1 %", type:"num"},
      {key:"ptbo_pre_hsct_fev1_z", label:"Pre-HSCT FEV1 z", type:"num"},
      {key:"ptbo_pre_hsct_fvc_pct", label:"Pre-HSCT FVC %", type:"num"},
      {key:"ptbo_pre_hsct_fvc_z", label:"Pre-HSCT FVC z", type:"num"},
      {key:"ptbo_pre_hsct_fev1_vc", label:"Pre-HSCT FEV1/VC", type:"num"},
      {key:"ptbo_pre_hsct_fef2575_pct", label:"Pre-HSCT FEF25-75 %", type:"num"},
      {key:"ptbo_pre_hsct_tlc", label:"Pre-HSCT TLC", type:"num"},
      {key:"ptbo_pre_hsct_rv", label:"Pre-HSCT RV", type:"num"},
      {key:"ptbo_pre_hsct_rv_tlc", label:"Pre-HSCT RV/TLC", type:"num"},
      {key:"ptbo_pre_hsct_dlco", label:"Pre-HSCT DLCO", type:"num"},
      {key:"ptbo_pre_hsct_lci", label:"Pre-HSCT MBW/LCI", type:"num"},
      {key:"ptbo_pre_hsct_ct_var", label:"Pre-HSCT inspiratuvar/ekspiratuvar BT", type:"bool"},
      {key:"ptbo_pre_hsct_ct_bulgu", label:"Pre-HSCT BT anomalileri", type:"text"},
    ]
  },
  ptbo_surveillance: {
    label: "HSCT kohortu - İzlem/PFT", registry:"PTBO", fields: [
      {key:"ptbo_survey_3ay_tarihi", label:"3. ay planlanan PFT", type:"date"},
      {key:"ptbo_survey_6ay_tarihi", label:"6. ay planlanan PFT", type:"date"},
      {key:"ptbo_survey_9ay_tarihi", label:"9. ay planlanan PFT", type:"date"},
      {key:"ptbo_survey_12ay_tarihi", label:"12. ay planlanan PFT", type:"date"},
      {key:"ptbo_gercek_pft_tarihleri", label:"Gerçek PFT tarihleri", type:"text"},
      {key:"ptbo_survey_tamamlik", label:"Surveillance tamamlık (%)", type:"num"},
      {key:"ptbo_survey_uyumlu", label:"Surveillance uyumlu/tamam", type:"bool"},
      {key:"ptbo_spirometri_yapabilir", label:"Spirometri yapabilir", type:"bool"},
      {key:"ptbo_mbw_lci_var", label:"MBW/LCI var", type:"bool"},
      {key:"ptbo_klinik_adjudikasyon_bos", label:"Klinisyen PTBO/BOS adjudikasyonu", type:"bool"},
    ]
  },
  ptbo_bos_eval: {
    label: "HSCT kohortu - BOS değerlendirme", registry:"PTBO", fields: [
      {key:"ptbo_bos_pozitif", label:"PTBO/BOS pozitif", type:"bool"},
      {key:"ptbo_bos_status", label:"PTBO/BOS durumu", type:"select", options:[{v:"no_bos",l:"BOS yok"},{v:"suspected",l:"Şüpheli PTBO/BOS"},{v:"probable",l:"Olası PTBO/BOS"},{v:"confirmed",l:"Doğrulanmış PTBO/BOS"},{v:"uncertain",l:"Belirsiz/alternatif tanı"}]},
      {key:"ptbo_bos_suphe_tarihi", label:"BOS şüphe tarihi", type:"date"},
      {key:"ptbo_bos_tani_tarihi", label:"BOS/PTBO tanı tarihi", type:"date"},
      {key:"ptbo_yeni_solunum_semptomu", label:"Yeni solunum semptomu", type:"bool"},
      {key:"ptbo_oksuruk", label:"Öksürük", type:"bool"},
      {key:"ptbo_dispne", label:"Dispne", type:"bool"},
      {key:"ptbo_wheezing", label:"Wheezing", type:"bool"},
      {key:"ptbo_hipoksemi", label:"Hipoksemi", type:"bool"},
      {key:"ptbo_egzersiz_intoleransi", label:"Egzersiz intoleransı", type:"bool"},
      {key:"ptbo_asemptomatik_pft_dusus", label:"Asemptomatik PFT düşüşü", type:"bool"},
      {key:"ptbo_bos_fev1_pct", label:"BOS şüphede FEV1 %", type:"num"},
      {key:"ptbo_fev1_dusus_iki_test", label:"FEV1 düşüşü ≥2 hafta arayla iki testte kalıcı", type:"bool"},
      {key:"ptbo_fev1_vc_lln_altinda", label:"FEV1/VC LLN altında", type:"bool"},
      {key:"ptbo_obstruktif_patern", label:"Obstrüktif patern", type:"bool"},
      {key:"ptbo_prism_patern", label:"PRISm-benzeri patern", type:"bool"},
      {key:"ptbo_rv_veya_rvtlc_uln_ustu", label:"RV veya RV/TLC ULN üstünde", type:"bool"},
      {key:"ptbo_lci", label:"LCI", type:"num"},
      {key:"ptbo_ct_air_trapping", label:"HRCT air trapping", type:"bool"},
      {key:"ptbo_ct_mozaik", label:"HRCT mozaik attenüasyon", type:"bool"},
      {key:"ptbo_ct_bronsektazi", label:"HRCT bronşektazi", type:"bool"},
      {key:"ptbo_ct_duvar_kalinlasma", label:"HRCT hava yolu duvar kalınlaşması", type:"bool"},
      {key:"ptbo_ct_infiltrat_enfeksiyon", label:"HRCT infiltrat/enfeksiyon paterni", type:"bool"},
      {key:"ptbo_bal_yapildi", label:"BAL yapıldı", type:"bool"},
      {key:"ptbo_bal_kultur", label:"BAL kültür", type:"text"},
      {key:"ptbo_bal_viral_pcr", label:"BAL viral/multiplex PCR", type:"text"},
      {key:"ptbo_bal_fungal_bakteriyel_tbc", label:"BAL fungal/bakteriyel/mikobakteri", type:"text"},
      {key:"ptbo_enfeksiyon_saptandi", label:"Enfeksiyon saptandı", type:"bool"},
      {key:"ptbo_enfeksiyon_tedavi_duzeldi", label:"Enfeksiyon tedavi edildi/rezolüsyon", type:"bool"},
      {key:"ptbo_enfeksiyon_sonrasi_suphe_devam", label:"Enfeksiyon sonrası BOS şüphesi devam", type:"bool"},
      {key:"ptbo_biyopsi_yapildi", label:"Akciğer biyopsisi yapıldı", type:"bool"},
      {key:"ptbo_biyopsi_endikasyon", label:"Biyopsi endikasyonu", type:"text"},
      {key:"ptbo_biyopsi_sonuc", label:"Biyopsi sonucu", type:"text"},
      {key:"ptbo_biyopsi_bo", label:"Biyopsi ile BO doğrulandı", type:"bool"},
      {key:"ptbo_klinisyen_son_tani", label:"Klinisyen final tanı", type:"select", options:[{v:"no_bos",l:"BOS yok"},{v:"suspected",l:"Şüpheli PTBO/BOS"},{v:"probable",l:"Olası PTBO/BOS"},{v:"confirmed_biopsy",l:"Biyopsi ile doğrulanmış BO"},{v:"uncertain",l:"Belirsiz/alternatif tanı"}]},
      {key:"ptbo_suspicion_flag", label:"PTBO/BOS şüphe bayrağı", type:"bool", readonly:true},
      {key:"ptbo_criteria_summary", label:"PTBO kriter özeti", type:"text", readonly:true},
      {key:"ptbo_diagnostic_category", label:"PTBO yardımcı kategori", type:"text", readonly:true},
      {key:"ptbo_supporting_features_count", label:"Destekleyici bulgu sayısı", type:"num", readonly:true},
      {key:"ptbo_missing_required_fields", label:"Eksik HSCT/BOS alanları", type:"text", readonly:true},
      {key:"ptbo_recommended_next_step", label:"Önerilen sonraki adım", type:"text", readonly:true},
    ]
  },
  ptbo_tedavi: {
    label: "HSCT kohortu - PTBO/BOS tedavi", registry:"PTBO", fields: [
      {key:"ptbo_ics", label:"İnhale kortikosteroid", type:"bool"},
      {key:"ptbo_bronkodilator_laba", label:"Bronkodilatör/LABA", type:"bool"},
      {key:"ptbo_azitromisin", label:"Azitromisin", type:"bool"},
      {key:"ptbo_montelukast", label:"Montelukast", type:"bool"},
      {key:"ptbo_fam_baslandi", label:"FAM başlandı", type:"bool"},
      {key:"ptbo_fam_baslama_tarihi", label:"FAM başlama tarihi", type:"date"},
      {key:"ptbo_sistemik_steroid_mgkg_gun", label:"Sistemik steroid mg/kg/gün", type:"num"},
      {key:"ptbo_sistemik_steroid_gun", label:"Sistemik steroid gün", type:"num"},
      {key:"ptbo_pulse_steroid", label:"Pulse steroid", type:"bool"},
      {key:"ptbo_ruxolitinib", label:"Ruxolitinib", type:"bool"},
      {key:"ptbo_belumosudil", label:"Belumosudil", type:"bool"},
      {key:"ptbo_abatacept", label:"Abatacept", type:"bool"},
      {key:"ptbo_axatilimab", label:"Axatilimab", type:"bool"},
      {key:"ptbo_ecp", label:"ECP", type:"bool"},
      {key:"ptbo_diger_immunsupresif", label:"Diğer immünsüpresif", type:"text"},
      {key:"ptbo_pulmoner_rehabilitasyon", label:"Pulmoner rehabilitasyon", type:"bool"},
      {key:"ptbo_gerd_degerlendirme_tedavi", label:"GERD değerlendirme/tedavi", type:"bool"},
      {key:"ptbo_antimikrobiyal_profilaksi", label:"Antimikrobiyal profilaksi", type:"bool"},
      {key:"ptbo_oksijen_destegi", label:"Oksijen desteği", type:"bool"},
      {key:"ptbo_niv_destegi", label:"NIV desteği", type:"bool"},
      {key:"ptbo_imv_destegi", label:"IMV desteği", type:"bool"},
      {key:"ptbo_akciger_tx_dusunuldu", label:"Akciğer nakli düşünüldü", type:"bool"},
      {key:"ptbo_akciger_tx_listelendi", label:"Akciğer nakli listelendi", type:"bool"},
      {key:"ptbo_akciger_tx_yapildi", label:"Akciğer nakli yapıldı", type:"bool"},
      {key:"ptbo_4hf_pft_tarihi", label:"Tedavi sonrası 4. hafta PFT tarihi", type:"date"},
      {key:"ptbo_tedavi_yanit", label:"Tedavi yanıtı", type:"select", options:[{v:"iyi",l:"İyi/stabil"},{v:"kismi",l:"Kısmi yanıt"},{v:"yanitsiz",l:"Yanıtsız/progresif"},{v:"exitus",l:"Exitus"}]},
    ]
  },
}

export function formFieldKeys(fieldGroups) {
  return Object.values(fieldGroups).flatMap(group => group.fields.map(field => field.key))
}
