alter table public.hastalar
  add column if not exists premature numeric,
  add column if not exists gestasyon_haftasi numeric,
  add column if not exists dogum_agirligi_g numeric,
  add column if not exists yenidogan_yogun_bakim numeric,
  add column if not exists neonatal_oksijen numeric,
  add column if not exists bpd_oykusu numeric,
  add column if not exists akut_asye_tarihi date,
  add column if not exists ates_suresi_gun numeric,
  add column if not exists agir_pnomoni numeric,
  add column if not exists ilk_akut_asye_yatis_gun numeric,
  add column if not exists tekrarlayan_pnomoni numeric,
  add column if not exists pnomoni_atak_sayisi numeric,
  add column if not exists toplam_pnomoni_yatis_gun numeric,
  add column if not exists akut_hipoksemi numeric,
  add column if not exists akut_yatis numeric,
  add column if not exists cocuk_yogun_bakim numeric,
  add column if not exists akut_oksijen numeric,
  add column if not exists akut_hfnc numeric,
  add column if not exists akut_niv numeric,
  add column if not exists akut_imv numeric,
  add column if not exists akut_ivig numeric,
  add column if not exists akut_glukokortikoid numeric,
  add column if not exists etken_mycoplasma numeric,
  add column if not exists etken_pnomokok numeric,
  add column if not exists etken_parainfluenza numeric,
  add column if not exists etken_bakteri numeric,
  add column if not exists koenfeksiyon numeric,
  add column if not exists etken_diger text,
  add column if not exists bt_mozaik numeric,
  add column if not exists bt_air_trapping numeric,
  add column if not exists bt_bronduvar_kalinlasma numeric,
  add column if not exists bt_buyuk_lobar_konsolidasyon numeric,
  add column if not exists bt_diffuz_bronsiolit numeric,
  add column if not exists imdef text,
  add column if not exists tani_surecinde_imyetm numeric,
  add column if not exists imdefdr text,
  add column if not exists atopik_dermatit numeric,
  add column if not exists kisisel_atopi numeric,
  add column if not exists aile_atopi numeric,
  add column if not exists spesifik_ige_pozitif numeric,
  add column if not exists iga_dusuk numeric,
  add column if not exists igm_dusuk numeric,
  add column if not exists igg_dusuk numeric,
  add column if not exists cd19 numeric,
  add column if not exists cd16_cd56 numeric,
  add column if not exists lswbc numeric,
  add column if not exists lslym_pct numeric,
  add column if not exists lscd3_pct numeric,
  add column if not exists lscd3_abs numeric,
  add column if not exists lscd4_pct numeric,
  add column if not exists lscd4_abs numeric,
  add column if not exists lscd8_pct numeric,
  add column if not exists lscd8_abs numeric,
  add column if not exists lscd4_cd8 numeric,
  add column if not exists lscd19 numeric,
  add column if not exists lscd56 numeric,
  add column if not exists bal_lenfosit_subset numeric,
  add column if not exists bal_lenfopeni numeric,
  add column if not exists bal_cd3 numeric,
  add column if not exists bal_cd4 numeric,
  add column if not exists bal_cd8 numeric,
  add column if not exists bal_cd4_cd8 numeric,
  add column if not exists bal_cd19 numeric,
  add column if not exists bal_cd16_cd56 numeric,
  add column if not exists bal_cd45 numeric,
  add column if not exists bal_cd56 numeric,
  add column if not exists bal_cd22 numeric,
  add column if not exists bal_cd20 numeric,
  add column if not exists bal_cd16 numeric,
  add column if not exists bal_cd3_hladr numeric,
  add column if not exists sistemik_steroid_mgkg_gun numeric,
  add column if not exists sistemik_steroid_gun numeric,
  add column if not exists sistemik_steroid_plan_gun numeric,
  add column if not exists kumulatif_sistemik_steroid_mgkg numeric,
  add column if not exists tanidan_once_antibiyotik numeric,
  add column if not exists flutikazon_neb_2mg_adet_gun numeric,
  add column if not exists flutikazon_neb_2mg_gun numeric,
  add column if not exists flutikazon_neb_05mg_adet_gun numeric,
  add column if not exists flutikazon_neb_05mg_gun numeric,
  add column if not exists flutikazon_neb_toplam_mcg numeric,
  add column if not exists flutikazon_inhaler_125_puff_gun numeric,
  add column if not exists flutikazon_inhaler_125_gun numeric,
  add column if not exists flutikazon_inhaler_50_puff_gun numeric,
  add column if not exists flutikazon_inhaler_50_gun numeric,
  add column if not exists flutikazon_inhaler_toplam_mcg numeric,
  add column if not exists seretide_125_puff_gun numeric,
  add column if not exists seretide_125_gun numeric,
  add column if not exists seretide_250_puff_gun numeric,
  add column if not exists seretide_250_gun numeric,
  add column if not exists seretide_aldi numeric,
  add column if not exists seretide_toplam_flutikazon_mcg numeric,
  add column if not exists toplam_inhale_steroid_mcg numeric,
  add column if not exists inhale_steroid_aldi numeric,
  add column if not exists fam_aldi numeric,
  add column if not exists azitromisin_aldi numeric,
  add column if not exists montelukast_aldi numeric,
  add column if not exists ivig_aldi numeric,
  add column if not exists ivig_aliyor numeric,
  add column if not exists ventolin_aldi numeric,
  add column if not exists sft_bas_tarihi date,
  add column if not exists sft_bit_tarihi date,
  add column if not exists akciger_goruntuleme_yapildi numeric,
  add column if not exists akciger_goruntuleme_tarihi date,
  add column if not exists akciger_goruntuleme_yontemi text,
  add column if not exists akciger_goruntuleme_bulgu text,
  add column if not exists ppd_mm numeric,
  add column if not exists ppd_sonuc text,
  add column if not exists tb_igra_sonuc text,
  add column if not exists tb_igra_tarihi date,
  add column if not exists tb_mikrobiyoloji_pozitif numeric,
  add column if not exists tb_tedavi_baslangic_tarihi date,
  add column if not exists tb_tedavi_suresi_ay numeric;

create table if not exists public.follow_up_visits (
  id uuid primary key default gen_random_uuid(),
  hasta_id text not null references public.hastalar(hasta_id) on delete cascade,
  visit_date date not null,
  takip_suresi_gun integer,
  takip_suresi_ay numeric,
  semptom_devam numeric,
  egzersiz_kisitliligi numeric,
  atak_sayisi numeric,
  pnomoni_sayisi numeric,
  o2 numeric,
  bipap numeric,
  imv numeric,
  ecmo numeric,
  yeni_oksijen_ihtiyaci numeric,
  va numeric,
  boy numeric,
  spo2 numeric,
  fev1 numeric,
  fvc numeric,
  mef2575 numeric,
  klinik_gidis text,
  klinik_gidis_otomatik text,
  notlar text,
  created_at timestamptz default now()
);

alter table public.follow_up_visits
  add column if not exists sistemik_steroid numeric,
  add column if not exists sistemik_steroid_mgkg_gun numeric,
  add column if not exists sistemik_steroid_gun numeric,
  add column if not exists sistemik_steroid_plan_gun numeric,
  add column if not exists kumulatif_sistemik_steroid_mgkg numeric;

create index if not exists follow_up_visits_hasta_id_visit_date_idx
  on public.follow_up_visits (hasta_id, visit_date desc);

create table if not exists public.pft_records (
  id uuid primary key default gen_random_uuid(),
  hasta_id text not null references public.hastalar(hasta_id) on delete cascade,
  test_date date not null,
  test_type text,
  tani_sonrasi_gun integer,
  tani_sonrasi_ay numeric,
  fev1 numeric,
  fev1_z numeric,
  fvc numeric,
  fvc_z numeric,
  fev1_fvc numeric,
  fev1_fvc_z numeric,
  mef2575 numeric,
  mef2575_z numeric,
  bd_fev1 numeric,
  bd_mef2575 numeric,
  dlco numeric,
  dlco_z numeric,
  rv numeric,
  tlc numeric,
  rv_tlc numeric,
  notlar text,
  created_at timestamptz default now()
);

create index if not exists pft_records_hasta_id_test_date_idx
  on public.pft_records (hasta_id, test_date desc);
